components:
  artifact_store:
    configuration: {}
    flavor: local
    id: dd6e05e2-1ec4-4c6f-8310-b3f8b55d4ea5
    is_shared: false
    name: default
    type: artifact_store
    user: 44fbed7a-9cf3-4bd2-8c8b-5e84573239ba
  experiment_tracker:
    configuration:
      databricks_host: null
      tracking_insecure_tls: false
      tracking_password: null
      tracking_token: null
      tracking_uri: null
      tracking_username: null
    flavor: mlflow
    id: 09a18e6c-4a62-4612-9001-809faea95205
    is_shared: false
    name: mlflow_tracker
    type: experiment_tracker
    user: 44fbed7a-9cf3-4bd2-8c8b-5e84573239ba
  model_deployer:
    configuration:
      service_path: ''
    flavor: mlflow
    id: a9353e10-99a9-4520-8f26-8e9fc495834e
    is_shared: false
    name: mlflow_deployer
    type: model_deployer
    user: 44fbed7a-9cf3-4bd2-8c8b-5e84573239ba
  orchestrator:
    configuration: {}
    flavor: local
    id: af780df8-fa01-41a5-bcb1-5e128e9e6fe7
    is_shared: false
    name: default
    type: orchestrator
    user: 44fbed7a-9cf3-4bd2-8c8b-5e84573239ba
stack_name: local_with_mlflow
zenml_version: 0.20.2
