wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.14
    start_time: 1665433816.626416
    t:
      1:
      - 5
      - 53
      - 55
      - 69
      2:
      - 5
      - 53
      - 55
      - 69
      3:
      - 2
      - 13
      - 15
      - 23
      4: 3.9.14
      5: 0.13.4
      8:
      - 5
